name: Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Node.js and pnpm environment
        uses: pnpm/setup@v2

      - name: Build plugin
        run: pnpm build

      - name: Find module.ts or module.tsx
        id: find-module-ts
        run: |
          MODULETS="$(find ./src -type f \( -name "module.ts" -o -name "module.tsx" \))"
          echo "modulets=${MODULETS}" >> $GITHUB_OUTPUT

      - name: Compatibility check
        uses: grafana/plugin-actions/is-compatible@is-compatible/v1.0.4
        with:
          module: ${{ steps.find-module-ts.outputs.modulets }}
          comment-pr: 'yes'
          fail-if-incompatible: 'no'
